# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_FINDUTILS_VERSION=4.9.0

FROM ghcr.io/awesome-containers/static-findutils:$STATIC_FINDUTILS_VERSION AS static-findutils
FROM ghcr.io/awesome-containers/alpine-build-essential:3.17 AS build

WORKDIR /src/findutils
COPY --from=static-findutils /bin/find /bin/locate /bin/updatedb /bin/xargs ./

RUN set -xeu; \
    for f in find locate xargs; do \
        strip -s -R .comment -R .gnu.version --strip-unneeded "$f"; \
        upx --no-progress --no-color "$f"; \
        upx -t --no-progress --no-color "$f"; \
        ! ldd "$f" && :; \
    done; \
    chmod -cR 755 ./*; \
    chown -cR 0:0 ./*; \
    ./find . --version

# slim static findutils image
FROM ghcr.io/awesome-containers/static-bash:$STATIC_BASH_VERSION-slim AS static-bash
COPY --from=build /src/findutils/ /bin/
